# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import UnityStreamer_pb2 as UnityStreamer__pb2


class UnityStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.stream_unary(
                '/unitystreamer.UnityStreamer/StreamData',
                request_serializer=UnityStreamer__pb2.UnityData.SerializeToString,
                response_deserializer=UnityStreamer__pb2.Received.FromString,
                )


class UnityStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnityStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=UnityStreamer__pb2.UnityData.FromString,
                    response_serializer=UnityStreamer__pb2.Received.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unitystreamer.UnityStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnityStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/unitystreamer.UnityStreamer/StreamData',
            UnityStreamer__pb2.UnityData.SerializeToString,
            UnityStreamer__pb2.Received.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
